export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_DOSAGES_LIST = "API_V1_DOSAGES_LIST"
export const API_V1_DOSAGES_LIST_SUCCEEDED = "API_V1_DOSAGES_LIST_SUCCEEDED"
export const API_V1_DOSAGES_LIST_FAILED = "API_V1_DOSAGES_LIST_FAILED"
export const API_V1_DOSAGES_CREATE = "API_V1_DOSAGES_CREATE"
export const API_V1_DOSAGES_CREATE_SUCCEEDED = "API_V1_DOSAGES_CREATE_SUCCEEDED"
export const API_V1_DOSAGES_CREATE_FAILED = "API_V1_DOSAGES_CREATE_FAILED"
export const API_V1_DOSAGES_READ = "API_V1_DOSAGES_READ"
export const API_V1_DOSAGES_READ_SUCCEEDED = "API_V1_DOSAGES_READ_SUCCEEDED"
export const API_V1_DOSAGES_READ_FAILED = "API_V1_DOSAGES_READ_FAILED"
export const API_V1_DOSAGES_UPDATE = "API_V1_DOSAGES_UPDATE"
export const API_V1_DOSAGES_UPDATE_SUCCEEDED = "API_V1_DOSAGES_UPDATE_SUCCEEDED"
export const API_V1_DOSAGES_UPDATE_FAILED = "API_V1_DOSAGES_UPDATE_FAILED"
export const API_V1_DOSAGES_PARTIAL_UPDATE = "API_V1_DOSAGES_PARTIAL_UPDATE"
export const API_V1_DOSAGES_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_DOSAGES_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_DOSAGES_PARTIAL_UPDATE_FAILED =
  "API_V1_DOSAGES_PARTIAL_UPDATE_FAILED"
export const API_V1_DOSAGES_DELETE = "API_V1_DOSAGES_DELETE"
export const API_V1_DOSAGES_DELETE_SUCCEEDED = "API_V1_DOSAGES_DELETE_SUCCEEDED"
export const API_V1_DOSAGES_DELETE_FAILED = "API_V1_DOSAGES_DELETE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_INDICATIONS_LIST = "API_V1_INDICATIONS_LIST"
export const API_V1_INDICATIONS_LIST_SUCCEEDED =
  "API_V1_INDICATIONS_LIST_SUCCEEDED"
export const API_V1_INDICATIONS_LIST_FAILED = "API_V1_INDICATIONS_LIST_FAILED"
export const API_V1_INDICATIONS_CREATE = "API_V1_INDICATIONS_CREATE"
export const API_V1_INDICATIONS_CREATE_SUCCEEDED =
  "API_V1_INDICATIONS_CREATE_SUCCEEDED"
export const API_V1_INDICATIONS_CREATE_FAILED =
  "API_V1_INDICATIONS_CREATE_FAILED"
export const API_V1_INDICATIONS_READ = "API_V1_INDICATIONS_READ"
export const API_V1_INDICATIONS_READ_SUCCEEDED =
  "API_V1_INDICATIONS_READ_SUCCEEDED"
export const API_V1_INDICATIONS_READ_FAILED = "API_V1_INDICATIONS_READ_FAILED"
export const API_V1_INDICATIONS_UPDATE = "API_V1_INDICATIONS_UPDATE"
export const API_V1_INDICATIONS_UPDATE_SUCCEEDED =
  "API_V1_INDICATIONS_UPDATE_SUCCEEDED"
export const API_V1_INDICATIONS_UPDATE_FAILED =
  "API_V1_INDICATIONS_UPDATE_FAILED"
export const API_V1_INDICATIONS_PARTIAL_UPDATE =
  "API_V1_INDICATIONS_PARTIAL_UPDATE"
export const API_V1_INDICATIONS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_INDICATIONS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_INDICATIONS_PARTIAL_UPDATE_FAILED =
  "API_V1_INDICATIONS_PARTIAL_UPDATE_FAILED"
export const API_V1_INDICATIONS_DELETE = "API_V1_INDICATIONS_DELETE"
export const API_V1_INDICATIONS_DELETE_SUCCEEDED =
  "API_V1_INDICATIONS_DELETE_SUCCEEDED"
export const API_V1_INDICATIONS_DELETE_FAILED =
  "API_V1_INDICATIONS_DELETE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_MEDICATIONS_LIST = "API_V1_MEDICATIONS_LIST"
export const API_V1_MEDICATIONS_LIST_SUCCEEDED =
  "API_V1_MEDICATIONS_LIST_SUCCEEDED"
export const API_V1_MEDICATIONS_LIST_FAILED = "API_V1_MEDICATIONS_LIST_FAILED"
export const API_V1_MEDICATIONS_CREATE = "API_V1_MEDICATIONS_CREATE"
export const API_V1_MEDICATIONS_CREATE_SUCCEEDED =
  "API_V1_MEDICATIONS_CREATE_SUCCEEDED"
export const API_V1_MEDICATIONS_CREATE_FAILED =
  "API_V1_MEDICATIONS_CREATE_FAILED"
export const API_V1_MEDICATIONS_READ = "API_V1_MEDICATIONS_READ"
export const API_V1_MEDICATIONS_READ_SUCCEEDED =
  "API_V1_MEDICATIONS_READ_SUCCEEDED"
export const API_V1_MEDICATIONS_READ_FAILED = "API_V1_MEDICATIONS_READ_FAILED"
export const API_V1_MEDICATIONS_UPDATE = "API_V1_MEDICATIONS_UPDATE"
export const API_V1_MEDICATIONS_UPDATE_SUCCEEDED =
  "API_V1_MEDICATIONS_UPDATE_SUCCEEDED"
export const API_V1_MEDICATIONS_UPDATE_FAILED =
  "API_V1_MEDICATIONS_UPDATE_FAILED"
export const API_V1_MEDICATIONS_PARTIAL_UPDATE =
  "API_V1_MEDICATIONS_PARTIAL_UPDATE"
export const API_V1_MEDICATIONS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MEDICATIONS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MEDICATIONS_PARTIAL_UPDATE_FAILED =
  "API_V1_MEDICATIONS_PARTIAL_UPDATE_FAILED"
export const API_V1_MEDICATIONS_DELETE = "API_V1_MEDICATIONS_DELETE"
export const API_V1_MEDICATIONS_DELETE_SUCCEEDED =
  "API_V1_MEDICATIONS_DELETE_SUCCEEDED"
export const API_V1_MEDICATIONS_DELETE_FAILED =
  "API_V1_MEDICATIONS_DELETE_FAILED"
export const API_V1_PARAMETERS_LIST = "API_V1_PARAMETERS_LIST"
export const API_V1_PARAMETERS_LIST_SUCCEEDED =
  "API_V1_PARAMETERS_LIST_SUCCEEDED"
export const API_V1_PARAMETERS_LIST_FAILED = "API_V1_PARAMETERS_LIST_FAILED"
export const API_V1_PARAMETERS_CREATE = "API_V1_PARAMETERS_CREATE"
export const API_V1_PARAMETERS_CREATE_SUCCEEDED =
  "API_V1_PARAMETERS_CREATE_SUCCEEDED"
export const API_V1_PARAMETERS_CREATE_FAILED = "API_V1_PARAMETERS_CREATE_FAILED"
export const API_V1_PARAMETERS_READ = "API_V1_PARAMETERS_READ"
export const API_V1_PARAMETERS_READ_SUCCEEDED =
  "API_V1_PARAMETERS_READ_SUCCEEDED"
export const API_V1_PARAMETERS_READ_FAILED = "API_V1_PARAMETERS_READ_FAILED"
export const API_V1_PARAMETERS_UPDATE = "API_V1_PARAMETERS_UPDATE"
export const API_V1_PARAMETERS_UPDATE_SUCCEEDED =
  "API_V1_PARAMETERS_UPDATE_SUCCEEDED"
export const API_V1_PARAMETERS_UPDATE_FAILED = "API_V1_PARAMETERS_UPDATE_FAILED"
export const API_V1_PARAMETERS_PARTIAL_UPDATE =
  "API_V1_PARAMETERS_PARTIAL_UPDATE"
export const API_V1_PARAMETERS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PARAMETERS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PARAMETERS_PARTIAL_UPDATE_FAILED =
  "API_V1_PARAMETERS_PARTIAL_UPDATE_FAILED"
export const API_V1_PARAMETERS_DELETE = "API_V1_PARAMETERS_DELETE"
export const API_V1_PARAMETERS_DELETE_SUCCEEDED =
  "API_V1_PARAMETERS_DELETE_SUCCEEDED"
export const API_V1_PARAMETERS_DELETE_FAILED = "API_V1_PARAMETERS_DELETE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
