# Generated by Django 2.2.17 on 2020-12-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tradename', models.CharField(max_length=256)),
                ('mechanism', models.TextField()),
                ('interactions', models.TextField()),
                ('indications', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medications_indications', to='home.CustomText')),
            ],
        ),
    ]
