# Generated by Django 2.2.17 on 2020-12-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_medications"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indications",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256)),
                ("info", models.TextField()),
                (
                    "dosages",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indications_dosages",
                        to="home.CustomText",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="medications",
            name="indications",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medications_indications",
                to="home.Indications",
            ),
        ),
    ]
